config/routes.rb
Rails.application.routes.draw do
  
  get 'home/index'
  root 'home#index'
  devise_for :users
  resources :cars

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :cars, only: [:index, :show]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord

    validates :model, presence: true
    validates :brand, presence: true
    validates :color, presence: true
    validates :year, presence: true
    validates :value, presence: true

    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :rememberable, :validatable
end

app/controllers/api/v1/cars_controller.rb
class Api::V1::CarsController < Api::V1::ApplicationController
    before_action :set_car, only: %i[ show ]

    def index
        @cars = Car.all
        render json: @cars
    end

    def show
        render json: @car
    end

    private 

    def set_car
        @car = Car.find(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

  # GET /cars or /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1 or /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars or /cars.json
  def create
    @car = cars_service.create(params: car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to car_url(@car), notice: "Car was successfully created." }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1 or /cars/1.json
  def update
    @car = cars_service.update(car_id: @car.id, params: car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to car_url(@car), notice: "Car was successfully updated." }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1 or /cars/1.json
  def destroy
    @car = cars_service.destroy(car_id: @car.id)

    respond_to do |format|
      format.html { redirect_to cars_url, notice: "Car was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def car_params
      params.require(:car).permit(:model, :brand, :color, :year, :value, :image)
    end

    def cars_service 
      @cars_service ||= CarService.new
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :block_access, except: [:destroy]

  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)

    if @user && @user.authenticate(params[:session][:password])
      sign_in(@user)
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def sign_in
        session[:user_id] = @user.id
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def block_access
        if current_user.present?
            redirect_to users_path
        end
    end

    def logged_in?
        !current_user.nil?
    end

    def sign_out
        session.delete(:user_id)
        @current_user = nil
    end
end
    

app/views/cars/_form.html.erb
<%= form_with(model: car, local: true) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "erro") %> não permitiu esse carro de ser salvo:</h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to I18n.t('menu.edit'), @car, class: "btn btn-warning" %> |
<%= link_to I18n.t('menu.back'), cars_path, class: "btn btn-danger" %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= I18n.t('cars.cars') %></h1>

<table class="table">
  <thead>
    <tr>
      <th><%= I18n.t('cars.model') %></th>
      <th><%= I18n.t('cars.brand') %></th>
      <th><%= I18n.t('cars.color') %></th>
      <th><%= I18n.t('cars.year') %></th>
      <th><%= I18n.t('cars.value') %></th>
      <th><%= I18n.t('cars.image') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <% if @cars.count < 1 %>
        <h2><%= I18n.t('cars.no_cars') %></h2>
      <% else %>
        <% @cars.each do |car| %>
          <tr>
            <td><%= car.model %></td>
            <td><%= car.brand %></td>
            <td><%= car.color %></td>
            <td><%= car.year %></td>
            <td><%= car.value %></td>
            <td><%= image_tag(car.image_url(:thumb).to_s) %></td>
            <% if user_signed_in? %>
              <td><%= link_to I18n.t('menu.show'), car, class: 'btn btn-primary'%></td>
              <td><%= link_to I18n.t('menu.edit'), edit_car_path(car), class: 'btn btn-warning' %></td>
              <td><%= link_to I18n.t('menu.destroy'), car, method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'btn btn-danger' %></td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
  <%= link_to I18n.t('cars.new'), new_car_path, class: 'btn btn-primary' %>
<% end %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to I18n.t('menu.back'), cars_path, class: "btn btn-primary" %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= I18n.t('cars.model') %>:</strong>
  <%= @car.model %>
</p>

<p>
  <strong><%= I18n.t('cars.brand') %>:</strong>
  <%= @car.brand %>
</p>

<p>
  <strong><%= I18n.t('cars.color') %>:</strong>
  <%= @car.color %>
</p>

<p>
  <strong><%= I18n.t('cars.year') %>:</strong>
  <%= @car.year %>
</p>

<p>
  <strong><%= I18n.t('cars.value') %>:</strong>
  <%= @car.value %>
</p>
<p>
  <strong><%= I18n.t('cars.image') %>:</strong>
  <%= image_tag(@car.image_url(:thumb).to_s) %>
</p>

<%= link_to I18n.t('menu.edit'), edit_car_path(@car), class: "btn btn-warning" %> |
<%= link_to I18n.t('menu.back'), cars_path, class: "btn btn-primary" %>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Seja bem-vindo!</h1>
  <p class="lead">Você está acessando o catálogo de carros da empresaX.</p>
  <hr class="my-4">
  <p>Para acessar o catálogo, clique no botão abaixo: </p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="/cars" role="button">Carros</a>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<%= nav_bar static: :top, responsive: true do %>
    <%= menu_group do %>
        <%= menu_item "Home", root_path %>
        <%= menu_item "Carros", cars_path %>
        <% if user_signed_in? %>
            <%= menu_item "Sair", destroy_user_session_path, method: :delete %>
        <% end %>
    <% end %>
<% end %>